version: '3.4'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app
    environment:
      - HOST
      - PORT
  webserver:
    image: nginx:1.25-bookworm
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - webroot:/var/www/html
      - ./nginx/conf:/etc/nginx/confd.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    environment:
      - SERVER
      - DOMAIN
    depends_on:
      - nodejs
    networks:
      - app
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal --staging -d ${DOMAIN}

networks:
  app:
    driver: bridge 

volumes:
  webroot:
  certbot-etc:
  certbot-var:
  dhparam: