version: '3.4'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs_${ENVIRONMENT}
    container_name: nodejs_${ENVIRONMENT}
    user: '1000:1000'
    restart: unless-stopped
    environment:
      - HOST
      - HTTP_PORT
      - HTTPS_PORT
      - DOMAIN
    volumes:
      - certbot-etc:/home/node/etc/letsencrypt:rw
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    ports:
      - "80:80"
      - "3000:3000"
  certbot:
    image: certbot/certbot
    container_name: certbot_${ENVIRONMENT}
    user: '1000:1000'
    volumes:
      - certbot-etc:/etc/letsencrypt:rw
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal ${STAGING} -d ${DOMAIN}

volumes:
  webroot:
  certbot-etc:
  certbot-var: